apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "micro-arch.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "micro-arch.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "micro-arch.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
