apiVersion: batch/v1
kind: Job
metadata:
  name: "myapp"
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "myapp"
    spec:
      restartPolicy: Never
      containers:
        - name: post-install-job
          image: postgres:15.4
          env:
            - name: DB_URL
              value: jdbc:postgresql://{{ include "postgresql.fullname" . }}:{{ .Values.postgresql.containerPorts.postgresql }}/{{ .Values.postgresql.auth.database }}
            - name: DB_USER
              value: {{ .Values.postgresql.auth.username }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: DB_PASSWORD
          command:
            - sh
            - "-c"
            - |
              psql postgres://myuser:passwd@micro-arch-postgresql/myapp <<'EOF'
                create table client (id bigint primary key, name varchar);
                insert into client (id, name) values (1, 'Stepan');
              EOF

  backoffLimit: 10

