apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: micro-arch
  labels:
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app: micro-arch
  endpoints:
    - port: actuator
      path: '/actuator/prometheus'
      interval: 15s
      honorLabels: true