# Default values for micro-arch.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: spacemancola/micro-arch
  tag: "0.1"

nameOverride: "micro-arch"
fullnameOverride: "micro-arch"

service:
  type: NodePort
  port: 80
  targetPort: 8000

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: arch.homework
      paths:
        - path: /
          pathType: ImplementationSpecific