# Default values for micro-arch.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: spacemancola/micro-arch

nameOverride: "micro-arch"
fullnameOverride: "micro-arch"

service:
  type: NodePort
  port: 80
  targetPort: 8000
  actuatorPort: 8081

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: arch.homework
      paths:
        - path: /
          pathType: ImplementationSpecific
          port: 80
        - path: /actuator
          pathType: ImplementationSpecific
          port: 8081
postgresql:
  enabled: true
  auth:
    postgresPassword: "postgres"
    username: "myuser"
    password: "passwd"
    database: "myapp"

dbDriverClassName: "org.postgresql.Driver"
